
version: '3.8'
services:
  mysql-dev:
    image: mysql:8.0
    container_name: mysql-dev
    env_file:
      - ./docker-env/mysql-dev.env
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    env_file:
      - ./docker-env/mysql-test.env
    ports:
      - 3307:3306

volumes:
  mysql-volume:
